import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-custom',
  templateUrl: './custom.component.html',
  styleUrls: ['./custom.component.css']
})
export class CustomComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }
  headers: any={
    thead:['UniqueID','Types','Sharedwith','Modificationdate','Status','Exp.date'],
    displayed:['id','type','connect','updatedate','status','validdate']
   }
   dataSource: any =
      [{
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      }
    ]

}
